import Head from 'next/head'
import axios from "axios";
import { useEffect,useState } from "react";
import { Inter } from 'next/font/google'
import Header from "../components/Header";
import Banner from "../components/Banner";
import BlockDataChip from "../components/BlockDataChip";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [blockData, setBlockData] = useState();
  
  useEffect(() => {
    axios.get("https://api.zksync.io/api/v0.2/blocks?from=latest&limit=10&direction=older").then((data) => {
      console.log(data.data)
      setBlockData(data.data);
    }).catch(err => {
      console.log(err);
    })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className + 'w-screen min-h-screen'}>
        <Header />
        <Banner />
         <div className="w-full px-8 md:px-[128px] py-10 text-xs">
        <BlockDataChip />
           </div>
      </main>
    </>
  )
}
